# ALL FEE VALUE ARE in EURO * 100 (basically, cents)
# All constant values related to fee or money has been applied with CENT_MULTIPLICATION_CONSTANT (100)
# this is for easier reading, issue with this is that changing things by float might be an issue
# Potential Issue: maybe CENT_MULTIPLICATION is NOT a good idea because of floating point issue and extra operation
CENT_MULTIPLICATION_CONSTANT = 100
MINIMUM_DELIVERY_FEE = 0
MAXIMUM_DELIVERY_FEE = 15 * CENT_MULTIPLICATION_CONSTANT
CART_VALUE_SURCHARGE = 10 * CENT_MULTIPLICATION_CONSTANT
RUSH_HOUR_CONSTANT = 1.2
INITIAL_DISTANCE = 1000
DISTANCE_PER_ADD_COST = 500
INITIAL_COST_BASED_DISTANCE = 2 * CENT_MULTIPLICATION_CONSTANT
ADD_COST_BASED_DISTANCE = 1 * CENT_MULTIPLICATION_CONSTANT
SURCHARGE_PER_EXTRA_ITEM = int(0.5 * CENT_MULTIPLICATION_CONSTANT)
BULK_CUTOFF_NUMBER_OF_ITEMS = 13  # number of items need to be more than or equal to BULK_CUTOFF
BULK_FEE = int(1.2 * CENT_MULTIPLICATION_CONSTANT)
MAX_SAFE_NUMBER_OF_ITEMS = 4
CART_VALUE_CUTOFF_FOR_FREE_DELIVERY_FEE = 100 * CENT_MULTIPLICATION_CONSTANT
